In [1]:
import pandas as pd
import numpy as np

### Machine Learning - Logistic Regression

In [2]:
# read preprocessed data
data = pd.read_csv("Absenteeism_preprocessed.csv")

In [3]:
data.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [4]:
data['Absenteeism Time in Hours'].median()

3.0

In [5]:
# class 1 is time in hours > 3
targets = np.where(data['Absenteeism Time in Hours'] > data['Absenteeism Time in Hours'].median(), 1, 0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data['Excessive Absenteeism'] = targets

data.head()

In [8]:
# proportion of class 1
targets.sum() / targets.shape[0]

0.45571428571428574

In [9]:
data_2 = data.drop(columns = ['Absenteeism Time in Hours', 'Day of the Week',
                             'Daily Work Load Average', 'Distance to Work'], axis = 1)

In [10]:
data_2.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

### Select inputs for the regression

In [11]:
data_2.shape

(700, 12)

In [12]:
data_2.iloc[:, :-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

In [13]:
unscaled_inputs = data_2.iloc[:, :-1]

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
from sklearn.base import BaseEstimator, TransformerMixin

class CustomScaler(BaseEstimator, TransformerMixin):
    
    def __init__(self, columns, copy = True, with_mean = True, with_std = True):
        self.scaler = StandardScaler(copy, with_mean, with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    def fit(self, X, y = None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis = 1)[init_col_order]

In [16]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [17]:
#columns_to_scale = ['Month Value',
#       'Day of the Week', 'Transportation Expense', 'Distance to Work',
#       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
#       'Children', 'Pets']

columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [18]:
absenteeism_scaler = CustomScaler(columns_to_scale)
absenteeism_scaler.fit(unscaled_inputs)
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

C:\Users\wooch\miniconda3\envs\cpsc330\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass copy=True, with_mean=True, with_std=True as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "


In [19]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.182726   
1           0         0         0         0     0.182726   
2           0         0         0         1     0.182726   
3           1         0         0         0     0.182726   
4           0         0         0         1     0.182726   
..        ...       ...       ...       ...          ...   
695         1         0         0         0    -0.388293   
696         1         0         0         0    -0.388293   
697         1         0         0         0    -0.388293   
698         0         0         0         1    -0.388293   
699         0         0         0         1    -0.388293   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

In [20]:
scaled_inputs.shape

(700, 11)

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 123)

In [23]:
x_train.shape

(560, 11)

In [24]:
x_test.shape

(140, 11)

### Logistic Regression

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [26]:
reg = LogisticRegression()

In [27]:
reg.fit(x_train, y_train)

LogisticRegression()

In [28]:
reg.score(x_train, y_train)

0.775

### Manually check the accuracy

In [29]:
# predictions
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,

In [30]:
model_outputs == y_train

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True, False,  True, False,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False,  True,  True, False,  True,  True,
        True,  True, False,  True, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True, False,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True, False,

In [31]:
np.sum((model_outputs == y_train))

434

In [32]:
model_outputs.shape[0]

560

In [33]:
np.sum((model_outputs == y_train)) / model_outputs.shape[0]

0.775

We get the same accuracy

### Intercept and Coefficients

In [34]:
reg.intercept_

array([-1.58313536])

In [35]:
reg.coef_

array([[ 2.80975862,  0.74492019,  3.02482701,  0.79534817,  0.14580932,
         0.61231181, -0.233286  ,  0.34263639, -0.22225673,  0.46156761,
        -0.31746703]])

In [36]:
feature_names = unscaled_inputs.columns.values

In [37]:
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_names)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                 Reason_1     2.809759
1                 Reason_2     0.744920
2                 Reason_3     3.024827
3                 Reason_4     0.795348
4              Month Value     0.145809
5   Transportation Expense     0.612312
6                      Age    -0.233286
7          Body Mass Index     0.342636
8                Education    -0.222257
9                 Children     0.461568
10                    Pets    -0.317467

In [38]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -1.583135
1                 Reason_1     2.809759
2                 Reason_2     0.744920
3                 Reason_3     3.024827
4                 Reason_4     0.795348
5              Month Value     0.145809
6   Transportation Expense     0.612312
7                      Age    -0.233286
8          Body Mass Index     0.342636
9                Education    -0.222257
10                Children     0.461568
11                    Pets    -0.317467

### Interpreting coefficients

In [39]:
# reason_1 = various diseases, reason_2 = pregnancy/maternity leave, reason_3 = poisoning, reason_4 = light diseases

summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)
summary_table.sort_values('Odds_ratio', ascending = False)

Feature name  Coefficient  Odds_ratio
3                 Reason_3     3.024827   20.590443
1                 Reason_1     2.809759   16.605909
4                 Reason_4     0.795348    2.215212
2                 Reason_2     0.744920    2.106273
6   Transportation Expense     0.612312    1.844691
10                Children     0.461568    1.586559
8          Body Mass Index     0.342636    1.408656
5              Month Value     0.145809    1.156976
9                Education    -0.222257    0.800710
7                      Age    -0.233286    0.791927
11                    Pets    -0.317467    0.727991
0                Intercept    -1.583135    0.205330

We can see that the 4 reasons have the biggest odds_ratio

### Testing

In [40]:
reg.score(x_test, y_test)

0.7

In [41]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.73687697, 0.26312303],
       [0.6205828 , 0.3794172 ],
       [0.78938282, 0.21061718],
       [0.89020816, 0.10979184],
       [0.85679862, 0.14320138],
       [0.81926388, 0.18073612],
       [0.76535619, 0.23464381],
       [0.32644266, 0.67355734],
       [0.76535619, 0.23464381],
       [0.78237815, 0.21762185],
       [0.42217998, 0.57782002],
       [0.54549683, 0.45450317],
       [0.76227659, 0.23772341],
       [0.56094019, 0.43905981],
       [0.29739759, 0.70260241],
       [0.12204698, 0.87795302],
       [0.41198572, 0.58801428],
       [0.53108072, 0.46891928],
       [0.75414649, 0.24585351],
       [0.30616899, 0.69383101],
       [0.82859321, 0.17140679],
       [0.24387311, 0.75612689],
       [0.78237815, 0.21762185],
       [0.06068372, 0.93931628],
       [0.34797952, 0.65202048],
       [0.07491241, 0.92508759],
       [0.02790516, 0.97209484],
       [0.36388388, 0.63611612],
       [0.251095  , 0.748905  ],
       [0.36405693, 0.63594307],
       [0.

In [42]:
predicted_proba.shape

(140, 2)

In [43]:
predicted_proba[:,1]

array([0.26312303, 0.3794172 , 0.21061718, 0.10979184, 0.14320138,
       0.18073612, 0.23464381, 0.67355734, 0.23464381, 0.21762185,
       0.57782002, 0.45450317, 0.23772341, 0.43905981, 0.70260241,
       0.87795302, 0.58801428, 0.46891928, 0.24585351, 0.69383101,
       0.17140679, 0.75612689, 0.21762185, 0.93931628, 0.65202048,
       0.92508759, 0.97209484, 0.63611612, 0.748905  , 0.63594307,
       0.4837768 , 0.10605697, 0.69680676, 0.18898611, 0.28404608,
       0.3084016 , 0.51566867, 0.21762185, 0.70055799, 0.4844563 ,
       0.4844563 , 0.95603645, 0.8431397 , 0.93257108, 0.71772736,
       0.25780995, 0.38470425, 0.70055799, 0.78294975, 0.75737053,
       0.14903247, 0.7112271 , 0.8431397 , 0.17140679, 0.63611612,
       0.63289865, 0.22296655, 0.45450317, 0.61324354, 0.75464621,
       0.15111406, 0.22002294, 0.34681491, 0.69175274, 0.21762185,
       0.39460445, 0.69680676, 0.5032445 , 0.64569664, 0.70040115,
       0.86276742, 0.21762185, 0.53676122, 0.15187586, 0.07048

### Saving the model with pickle

In [44]:
import pickle

In [45]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [46]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)